'use server';

import { addEvent as sheetAddEvent } from "@/lib/sheetdb";
import { logAdminAction, verifyAdmin } from "@/lib/actions/admin";
import { EconomicEvent } from "@/lib/types";

export async function createEconomicEvent(eventData: EconomicEvent) {
    const isAdmin = await verifyAdmin();
    if (!isAdmin) {
        throw new Error("Unauthorized: Admin access required");
    }

    try {
        // Remove ID if present as it's generated by sheetdb helper
        const { id, ...eventPayload } = eventData as any;

        await sheetAddEvent(eventPayload);

        await logAdminAction('ADD_EVENT', null, {
            event: eventData.event,
            date: eventData.date
        });

        return { success: true };
    } catch (error: any) {
        console.error("Failed to add event:", error);
        throw new Error(error.message || "Failed to add event");
    }
}
